default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  user: tonio
  password: 348260830
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: abc_sandbox

test:
  <<: *default
  database: abc_sandbox

production:
  <<: *default
  database: abc_sandbox
